### ISSUE TITLE
Magical trait conflict

### ISSUE THREAD

**Issue by RCXcrafter** [ToMe25/ToMeTinkers#3]
**Describe the bug**
The magical trait from this mod has the same id as the magical trait from [simple tcon](https://minecraft.curseforge.com/projects/simple-tcon)

**To Reproduce**
1. load [simple tcon](https://minecraft.curseforge.com/projects/simple-tcon) and this mod at the same time

**Enviroment:**
 - MC Version 1.12.2
 - Forge Version 14.23.5.2811
 - Mod Version 1.12.2-1.1
 - Other Loaded Mods Simple Tcon 3.0a

**Additional context**
Here's how to actually fix this: simply change the id of the magical trait to "tomemagical" for example.

**Comment by ToMe25** [comment]
I will rename it to "tometinkers_magical" but i need to test some things to maybe fix tools with the old id.

**Comment by ToMe25** [comment]
@RCXcrafter I fixed this Bug some time ago but i needed more time after that to fix another Bug :)
